global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using Ordering.Domain.Enums;
global using Ordering.Domain.Abastractions;
global using Ordering.Infrastructure.Data;
global using Ordering.Infrastructure.Data.Interceptors;
global using Ordering.Application.Data;